### ISSUE TITLE
styleAttr为Horizontal 时无法铺满全屏

### ISSUE THREAD

**Issue by 425765923** [react-native-oh-library/progress-bar-android#4]
styleAttr为Horizontal 时无法铺满全屏，如下图右侧有留白部分
![image](https://github.com/react-native-oh-library/progress-bar-android/assets/27410042/b7119184-8c2b-412f-a3ec-14b1beb991d4)

代码为：
`    <View style={{width:'100%',height:'100%',paddingTop:50}}>
    <ProgressBar styleAttr="Horizontal" indeterminate={false} animating={false} />
    <ProgressBar styleAttr="Horizontal" indeterminate={false} animating={true} />
    <ProgressBar styleAttr="Horizontal" indeterminate={false} animating={true} progress={0.5} />
    <ProgressBar styleAttr="Horizontal" indeterminate={true} animating={true}  />
    <ProgressBar styleAttr="Horizontal" color="black" />
    <ProgressBar styleAttr="Horizontal" indeterminate={true} color="blue" />
    </View>`

**Comment by dp19960202** [comment]
progress-bar-android依赖鸿蒙三方库materialprogressbar，更新materialprogressbar版本为2.0.3-rc.0,progress-bar-android设置styleAttr 为 Horizontal 时无法铺满全屏问题得到解决。
